const APP_META=Object.freeze({version:'1.2.0',build:'2026-09-13.1',channel:'Stable'});
const C=FinanceCore;

const PIN_KEY='finance-os-pin-v1';
function bytesHex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function pinHash(pin,salt){const data=new TextEncoder().encode(salt+':'+pin);return bytesHex(await crypto.subtle.digest('SHA-256',data))}
function pinConfig(){try{return JSON.parse(localStorage.getItem(PIN_KEY)||'null')}catch{return null}}
async function setPin(){const a=prompt('Crie um PIN de 4 a 8 números:');if(a===null)return;if(!/^\d{4,8}$/.test(a))return alert('Use de 4 a 8 números.');const b=prompt('Repita o PIN:');if(a!==b)return alert('Os PINs não conferem.');const salt=crypto.getRandomValues(new Uint32Array(4)).join('-');localStorage.setItem(PIN_KEY,JSON.stringify({salt,hash:await pinHash(a,salt),createdAt:new Date().toISOString()}));updatePinStatus();showToast('PIN ativado neste aparelho.')}
async function removePin(){const cfg=pinConfig();if(!cfg)return showToast('Nenhum PIN configurado.');const p=prompt('Digite o PIN atual para remover:');if(p===null)return;if(await pinHash(p,cfg.salt)!==cfg.hash)return alert('PIN incorreto.');localStorage.removeItem(PIN_KEY);updatePinStatus();showToast('PIN removido.')}
function updatePinStatus(){const on=!!pinConfig();if($('#pinStatus'))$('#pinStatus').textContent=on?'PIN ativo neste aparelho.':'PIN desativado.';if($('#removePinBtn'))$('#removePinBtn').disabled=!on;if($('#lockNowBtn'))$('#lockNowBtn').disabled=!on}
function lockApp(){if(!pinConfig())return;$('#lockScreen').classList.remove('hidden');$('#unlockPin').value='';$('#unlockError').textContent='';setTimeout(()=>$('#unlockPin').focus(),50)}
async function unlockApp(){const cfg=pinConfig();if(!cfg){$('#lockScreen').classList.add('hidden');return}const pin=$('#unlockPin').value;if(await pinHash(pin,cfg.salt)===cfg.hash){$('#lockScreen').classList.add('hidden');$('#unlockPin').value='';$('#unlockError').textContent=''}else{$('#unlockError').textContent='PIN incorreto.';$('#unlockPin').select()}}
let hiddenAt=0;document.addEventListener('visibilitychange',()=>{if(document.hidden)hiddenAt=Date.now();else if(pinConfig()&&hiddenAt&&Date.now()-hiddenAt>120000)lockApp()});
window.addEventListener('error',e=>{console.error(e.error||e.message);showToast('Algo deu errado. Seus dados não foram apagados.')});
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);showToast('Não foi possível concluir essa ação.')});

const DB='finance-os-db',VER=4;const stores=['transactions','recurring','installments','cards','meta'];
const categories=[['moradia','🏠 Moradia'],['mercado','🛒 Mercado'],['alimentacao','🍔 Alimentação fora'],['bebidas','🍺 Bebidas'],['transporte','🚗 Transporte'],['saude','🩺 Saúde'],['pessoal','👕 Roupas e pessoal'],['lazer','🎮 Lazer'],['viagens','✈️ Viagens'],['assinaturas','📱 Assinaturas e serviços'],['educacao','📚 Educação'],['pets','🐶 Pets'],['familia','🎁 Presentes e família'],['juros','💳 Juros e taxas'],['compras','📦 Compras diversas'],['outros','❓ Outros']];
const incomeSources=[['salario','💼 Salário'],['particular','🧠 Atendimento particular'],['tiktok','🎵 TikTok Shop'],['extra','✨ Renda extra'],['venda','🏷️ Venda'],['reembolso','↩️ Reembolso'],['rendimentos','📈 Rendimentos'],['presente','🎁 Presente'],['outros','💵 Outros']];
const subcategories={moradia:['Aluguel','Água','Luz','Gás','Condomínio','Manutenção','Móveis/Eletro'],mercado:['Supermercado','Açougue','Feira','Padaria','Casa'],alimentacao:['Delivery','Restaurante','Lanche','Café'],bebidas:['Bar','Cerveja','Refrigerante','Energético'],transporte:['Combustível','Uber/99','Estacionamento','Pedágio','Manutenção','Seguro','IPVA'],saude:['Farmácia','Consulta','Exames','Plano','Dentista'],pessoal:['Roupas','Tênis','Acessórios','Barbeiro','Cosméticos'],lazer:['Cinema','Jogos','Eventos','Hobbies'],assinaturas:['Streaming','Celular','Internet','Apps'],pets:['Ração','Veterinário','Medicamentos','Banho/Tosa'],compras:['Eletrônicos','Casa','Marketplace','Outros']};
let db,state={transactions:[],recurring:[],installments:[],cards:[]},currentMonth=C.ym(C.ymd());
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{for(const s of stores)if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:s==='meta'?'key':'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function clearStore(store){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function refresh(){state.transactions=await all('transactions');state.recurring=await all('recurring');state.installments=await all('installments');state.cards=await all('cards');render();refreshCardSelects()}

function syncAppMeta(){
  const v=$('#appVersion'),b=$('#appBuild'),c=$('#appChannel'),f=$('#versionFooter');
  if(v)v.textContent='v'+APP_META.version;if(b)b.textContent=APP_META.build;if(c)c.textContent=APP_META.channel;if(f)f.textContent=`Finance OS • v${APP_META.version}`;
}
function syncPaymentUI(value){
  const wanted=value||$('#txPayment')?.value||'Pix';
  if($('#txPayment'))$('#txPayment').value=wanted;
  $$('[data-payment]').forEach(b=>b.classList.toggle('active',b.dataset.payment===wanted));
  const credit=wanted==='Crédito';
  if($('#txCardWrap'))$('#txCardWrap').classList.toggle('hidden',!credit);
  if(!credit&&$('#txCard'))$('#txCard').value='';
}
function resetTxForm(type){
  $('#txForm').reset();$('#txEditId').value='';$('#txType').value=type;$('#txTitle').textContent=type==='income'?'Nova entrada':'Novo gasto';
  $('#incomeSourceWrap').classList.toggle('hidden',type!=='income');$('#txDate').value=C.ymd();
  fillSubcat($('#txSubcategory'),$('#txCategory').value);refreshCardSelects();syncPaymentUI('Pix');
}

function refreshCardSelects(){const html='<option value="">Sem cartão</option>'+state.cards.filter(x=>!x.deletedAt).map(x=>`<option value="${x.id}">${x.name}</option>`).join('');if($('#txCard'))$('#txCard').innerHTML=html;if($('#instCard'))$('#instCard').innerHTML=html}
function categoryName(id){return categories.find(x=>x[0]===id)?.[1]||'❓ Outros'}
function subcatOptions(cat){return [''].concat(subcategories[cat]||[])}
function fillSubcat(el,cat,value=''){el.innerHTML=subcatOptions(cat).map(v=>`<option value="${v}">${v||'Sem subcategoria'}</option>`).join('');el.value=value||''}
function sourceName(id){return incomeSources.find(x=>x[0]===id)?.[1]||'Outros'}
function fmtMonth(ym){const [y,m]=ym.split('-').map(Number);return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function fillSelect(el,items){el.innerHTML=items.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}
function navigate(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='movements')renderMovements();if(v==='analysis')renderAnalysis()}
function render(){const p=C.monthProjection(state,currentMonth);$('#monthLabel').textContent=fmtMonth(currentMonth);$('#freeMoney').textContent=C.money(p.free);$('#freeHint').textContent=p.free>=0?'✨ Depois de considerar tudo o que ainda vem pela frente.':'⚠️ Atenção: o mês está projetado no negativo.';$('#incomeMetric').textContent=C.money(p.totalIncome);$('#expenseMetric').textContent=C.money(p.expenseActual);$('#committedMetric').textContent=C.money(p.expensePlanned);renderBars('#categoryBars');renderUpcoming();renderMovements();renderAnalysis()}
function renderBars(sel){const rows=C.categoryBreakdown(state,currentMonth),max=Math.max(1,...rows.map(x=>x.amountCents));$(sel).innerHTML=rows.length?rows.slice(0,8).map(x=>`<div class="bar-card"><div class="bar-row"><b>${categoryName(x.categoryId)}</b><span>${C.money(x.amountCents)}</span><div class="track"><div class="fill" style="width:${Math.max(4,x.amountCents/max*100)}%"></div></div></div></div>`).join(''):`<div class="empty-state"><span class="emoji">🌱</span><b>Nenhum gasto por aqui</b><small>Quando você lançar um gasto, ele aparece organizado por categoria.</small></div>`}
function renderUpcoming(){const p=C.monthProjection(state,currentMonth),today=C.ymd();const rows=p.planned.filter(x=>x.type==='expense'&&x.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,6);$('#upcomingList').innerHTML=rows.length?rows.map(x=>`<div class="card"><div><b>${x.description||categoryName(x.categoryId)}</b><small>${new Date(x.date+'T12:00:00').toLocaleDateString('pt-BR')}${x.count?` · ${x.number}/${x.count}`:''}</small></div><strong class="amount expense">${C.money(x.amountCents)}</strong></div>`).join(''):`<div class="empty-state"><span class="emoji">✨</span><b>Agenda financeira limpa</b><small>Nenhum compromisso futuro cadastrado neste mês.</small></div>`}
function movementRows(){const p=C.monthProjection(state,currentMonth);const actual=p.transactions.map(x=>({...x,planned:false}));const planned=p.planned.map(x=>({...x,planned:true}));return [...actual,...planned].sort((a,b)=>b.date.localeCompare(a.date))}
function renderMovements(){$('#movementMonth').textContent=fmtMonth(currentMonth);const rows=movementRows();$('#movementList').innerHTML=rows.length?rows.map(x=>`<div class="card"><div><b>${x.description||categoryName(x.categoryId)}</b><small>${new Date(x.date+'T12:00:00').toLocaleDateString('pt-BR')} · ${x.planned?'⏳ Previsto':x.type==='income'?'✅ Recebido':'✅ Pago'}${x.subcategory?' · '+x.subcategory:''}${x.number?` · ${x.number}/${x.count}`:''}</small></div><div class="move-side"><strong class="amount ${x.type==='income'?'income':'expense'}">${x.type==='income'?'+':'−'} ${C.money(x.amountCents)}</strong>${x.planned?`<button class="mini" data-pay="${x.id}">✓ Pagar</button>`:`<div><button class="mini" data-edit="${x.id}">Editar</button><button class="mini danger" data-del="${x.id}">Excluir</button></div>`}</div></div>`).join(''):`<div class="empty-state"><span class="emoji">🧾</span><b>Nada lançado ainda</b><small>Use o botão + para adicionar uma entrada, gasto, conta fixa ou parcelamento.</small></div>`;$$('[data-edit]').forEach(b=>b.onclick=()=>editTx(b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=()=>deleteTx(b.dataset.del));$$('[data-pay]').forEach(b=>b.onclick=()=>payPlanned(b.dataset.pay))}
async function deleteTx(id){const x=state.transactions.find(t=>t.id===id);if(!x||!confirm(`Excluir ${x.description}?`))return;await put('transactions',{...x,deletedAt:new Date().toISOString()});await refresh();showToast('Movimentação excluída.')}
function editTx(id){const x=state.transactions.find(t=>t.id===id);if(!x)return;$('#txEditId').value=x.id;$('#txType').value=x.type;$('#txTitle').textContent=x.type==='income'?'Editar entrada':'Editar gasto';$('#txAmount').value=(x.amountCents/100).toFixed(2).replace('.',',');$('#txDescription').value=x.description;$('#txCategory').value=x.categoryId||'outros';fillSubcat($('#txSubcategory'),$('#txCategory').value,x.subcategory);$('#txIncomeSource').value=x.incomeSource||'outros';$('#incomeSourceWrap').classList.toggle('hidden',x.type!=='income');$('#txDate').value=x.date;$('#txPayment').value=x.paymentMethod||'Pix';$('#txCard').value=x.cardId||'';syncPaymentUI($('#txPayment').value);if(x.cardId)$('#txCardWrap').classList.remove('hidden');open('txDialog')}
async function payPlanned(id){const x=movementRows().find(t=>t.id===id&&t.planned);if(!x)return;let amount=x.amountCents;if(x.variable){const v=prompt(`Valor real de ${x.description}:`,(amount/100).toFixed(2).replace('.',','));if(v===null)return;amount=C.toCents(v);if(amount<=0)return alert('Informe um valor válido.')}await put('transactions',{id:C.uid('tx'),type:x.type,amountCents:amount,description:x.description,categoryId:x.categoryId,subcategory:x.subcategory||'',date:x.date,paymentMethod:'Outro',status:'paid',recurringId:x.recurringId||'',purchaseId:x.purchaseId||'',installmentNumber:x.installmentNumber||x.number||0,cardId:x.cardId||'',createdAt:new Date().toISOString()});await refresh();showToast(x.type==='income'?'Entrada confirmada.':'Pagamento confirmado.')}
function renderAnalysis(){const p=C.monthProjection(state,currentMonth);$('#analysisText').textContent=`Você tem ${C.money(p.totalIncome)} previstos de entrada e ${C.money(p.totalExpense)} entre gastos já realizados e compromissos do mês. Seu dinheiro livre projetado é ${C.money(p.free)}.`;renderBars('#analysisBars');const tx=p.transactions.filter(x=>x.type==='income');const rec=p.planned.filter(x=>x.type==='income');const map=new Map();for(const x of [...tx,...rec]){const k=x.incomeSource||'outros';map.set(k,(map.get(k)||0)+x.amountCents)}$('#incomeSources').innerHTML=map.size?[...map.entries()].sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="card"><b>${sourceName(k)}</b><strong class="amount income">${C.money(v)}</strong></div>`).join(''):`<div class="empty-state"><span class="emoji">💰</span><b>Nenhuma entrada cadastrada</b><small>Suas fontes de renda vão aparecer aqui.</small></div>`}
function open(id){document.getElementById(id).showModal()}function close(id){document.getElementById(id).close()}
async function saveTx(e){e.preventDefault();const type=$('#txType').value;const editId=$('#txEditId').value;const prior=editId?state.transactions.find(x=>x.id===editId):null;await put('transactions',{...(prior||{}),id:editId||C.uid('tx'),type,amountCents:C.toCents($('#txAmount').value),description:$('#txDescription').value.trim(),categoryId:$('#txCategory').value,subcategory:$('#txSubcategory').value,incomeSource:type==='income'?$('#txIncomeSource').value:'',date:$('#txDate').value,paymentMethod:$('#txPayment').value,cardId:$('#txCard').value,status:'paid',createdAt:prior?.createdAt||new Date().toISOString(),updatedAt:editId?new Date().toISOString():''});$('#txEditId').value='';close('txDialog');e.target.reset();await refresh();showToast(type==='income'?'Entrada salva.':'Gasto salvo.')}
async function saveRecurring(e){e.preventDefault();const editId=$('#recEditId').value,prior=editId?state.recurring.find(x=>x.id===editId):null;await put('recurring',{...(prior||{}),id:editId||C.uid('rec'),type:'expense',description:$('#recDescription').value.trim(),amountCents:C.toCents($('#recAmount').value),categoryId:$('#recCategory').value,subcategory:$('#recSubcategory').value,variable:$('#recVariable').checked,day:Number($('#recDay').value),startDate:$('#recStart').value,endDate:$('#recEnd').value,active:true,frequency:'monthly',createdAt:prior?.createdAt||new Date().toISOString(),updatedAt:editId?new Date().toISOString():''});$('#recEditId').value='';close('recDialog');e.target.reset();await refresh();showToast(editId?'Conta recorrente atualizada.':'Conta recorrente salva.')}
function updateInstPreview(){const total=C.toCents($('#instTotal').value),count=Number($('#instCount').value)||0;if(total&&count>1){const base=Math.floor(total/count);$('#instPreview').textContent=`${count}x de aproximadamente ${C.money(base)}. A última parcela absorve qualquer diferença de centavos.`}else $('#instPreview').textContent=''}
async function saveInstallment(e){e.preventDefault();const editId=$('#instEditId').value,prior=editId?state.installments.find(x=>x.id===editId):null,total=C.toCents($('#instTotal').value),count=Number($('#instCount').value),base=Math.floor(total/count);await put('installments',{...(prior||{}),id:editId||C.uid('inst'),description:$('#instDescription').value.trim(),totalCents:total,installmentCents:base,count,startDate:$('#instStart').value,categoryId:$('#instCategory').value,subcategory:$('#instSubcategory').value,cardId:$('#instCard').value,createdAt:prior?.createdAt||new Date().toISOString(),updatedAt:editId?new Date().toISOString():''});$('#instEditId').value='';close('instDialog');e.target.reset();await refresh();showToast(editId?'Parcelamento atualizado.':'Parcelamento criado.')}
function showList(kind){const recurring=kind==='recurring';$('#listTitle').textContent=recurring?'Contas recorrentes':'Compras parceladas';const rows=(recurring?state.recurring:state.installments).filter(x=>!x.deletedAt);$('#listContent').innerHTML=rows.length?rows.map(x=>{if(recurring)return `<div class="card manage-card"><div><b>${x.description}</b><small>${C.money(x.amountCents)} · dia ${x.day} · ${x.variable?'valor variável · ':''}${x.endDate?'até '+new Date(x.endDate+'T12:00:00').toLocaleDateString('pt-BR'):'sem data final'}</small></div><div><button class="mini" data-edit-rec="${x.id}">Editar</button><button class="mini danger" data-del-rec="${x.id}">Excluir</button></div></div>`;const r=C.remainingInstallments(x);return `<div class="card manage-card"><div><b>${x.description}</b><small>${x.count}x · termina ${r.endDate?new Date(r.endDate+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</small></div><div class="manage-actions"><strong>${C.money(x.totalCents)}</strong><div><button class="mini" data-edit-inst="${x.id}">Editar</button><button class="mini danger" data-del-inst="${x.id}">Excluir</button></div></div></div>`}).join(''):`<div class="card"><small>Nenhum cadastro ainda.</small></div>`;$$('[data-edit-rec]').forEach(b=>b.onclick=()=>editRecurring(b.dataset.editRec));$$('[data-del-rec]').forEach(b=>b.onclick=()=>deleteManaged('recurring',b.dataset.delRec));$$('[data-edit-inst]').forEach(b=>b.onclick=()=>editInstallment(b.dataset.editInst));$$('[data-del-inst]').forEach(b=>b.onclick=()=>deleteManaged('installments',b.dataset.delInst));open('listDialog')}
async function saveCard(e){e.preventDefault();const editId=$('#cardEditId').value,prior=editId?state.cards.find(x=>x.id===editId):null;const obj={...(prior||{}),id:editId||C.uid('card'),name:$('#cardName').value.trim(),limitCents:C.toCents($('#cardLimit').value),closingDay:Number($('#cardClosing').value),dueDay:Number($('#cardDue').value),createdAt:prior?.createdAt||new Date().toISOString(),updatedAt:editId?new Date().toISOString():''};if(!obj.name||obj.limitCents<=0)return alert('Confira nome e limite.');await put('cards',obj);$('#cardEditId').value='';e.target.reset();close('cardDialog');await refresh();showToast(editId?'Cartão atualizado.':'Cartão cadastrado.')}
function showCards(){const rows=state.cards.filter(x=>!x.deletedAt);$('#listTitle').textContent='Cartões';$('#listContent').innerHTML=rows.length?rows.map(x=>{const st=C.cardStatement(state,x,currentMonth);return `<div class="card manage-card"><div><b>${x.name}</b><small>Fecha dia ${x.closingDay} · vence dia ${x.dueDay}<br>Fatura ${C.money(st.totalCents)} · disponível ${C.money(st.availableLimitCents)}</small></div><div class="manage-actions"><strong>${C.money(x.limitCents)}</strong><div><button class="mini" data-edit-card="${x.id}">Editar</button><button class="mini danger" data-del-card="${x.id}">Excluir</button></div></div></div>`}).join(''):'<div class="card"><small>Nenhum cartão cadastrado.</small></div>';$$('[data-edit-card]').forEach(b=>b.onclick=()=>editCard(b.dataset.editCard));$$('[data-del-card]').forEach(b=>b.onclick=()=>deleteManaged('cards',b.dataset.delCard));open('listDialog')}

function editRecurring(id){const x=state.recurring.find(t=>t.id===id&&!t.deletedAt);if(!x)return;close('listDialog');$('#recEditId').value=x.id;$('#recDialogTitle').textContent='Editar conta recorrente';$('#recDescription').value=x.description;$('#recAmount').value=(x.amountCents/100).toFixed(2).replace('.',',');$('#recCategory').value=x.categoryId||'outros';fillSubcat($('#recSubcategory'),$('#recCategory').value,x.subcategory);$('#recVariable').checked=!!x.variable;$('#recDay').value=x.day;$('#recStart').value=x.startDate;$('#recEnd').value=x.endDate||'';open('recDialog')}
function editInstallment(id){const x=state.installments.find(t=>t.id===id&&!t.deletedAt);if(!x)return;close('listDialog');$('#instEditId').value=x.id;$('#instDialogTitle').textContent='Editar compra parcelada';$('#instDescription').value=x.description;$('#instTotal').value=(x.totalCents/100).toFixed(2).replace('.',',');$('#instCount').value=x.count;$('#instStart').value=x.startDate;$('#instCategory').value=x.categoryId||'outros';fillSubcat($('#instSubcategory'),$('#instCategory').value,x.subcategory);$('#instCard').value=x.cardId||'';updateInstPreview();open('instDialog')}
function editCard(id){const x=state.cards.find(t=>t.id===id&&!t.deletedAt);if(!x)return;close('listDialog');$('#cardEditId').value=x.id;$('#cardDialogTitle').textContent='Editar cartão';$('#cardName').value=x.name;$('#cardLimit').value=(x.limitCents/100).toFixed(2).replace('.',',');$('#cardClosing').value=x.closingDay;$('#cardDue').value=x.dueDay;open('cardDialog')}
async function deleteManaged(store,id){const map={recurring:'conta recorrente',installments:'parcelamento',cards:'cartão'},rows=state[store]||[],x=rows.find(t=>t.id===id&&!t.deletedAt);if(!x||!confirm(`Excluir ${map[store]} "${x.description||x.name}"? O histórico já pago será preservado.`))return;await put(store,{...x,deletedAt:new Date().toISOString(),active:false});await refresh();close('listDialog');if(store==='cards')showCards();else showList(store==='recurring'?'recurring':'installments');showToast(`${map[store][0].toUpperCase()+map[store].slice(1)} excluído.`)}

async function exportBackup(){const env=await C.createBackupEnvelope(state);const blob=new Blob([JSON.stringify(env,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`finance-os-backup-${C.ymd()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#backupStatus').textContent='Backup exportado agora.'}
async function importBackup(file){try{const parsed=JSON.parse(await file.text());const v=await C.validateBackupEnvelope(parsed);if(!v.ok)throw new Error(v.errors.join('\n'));if(!confirm('Restaurar este backup vai substituir os dados atuais deste aparelho. Continuar?'))return;for(const s of ['transactions','recurring','installments','cards']){await clearStore(s);for(const obj of v.data[s]||[])await put(s,obj)}await refresh();$('#backupStatus').textContent='Backup restaurado com sucesso.';showToast('Backup restaurado.')}catch(e){alert('Não foi possível restaurar o backup.\n\n'+e.message)}}
function bind(){fillSelect($('#txCategory'),categories);fillSelect($('#recCategory'),categories);fillSelect($('#instCategory'),categories);fillSelect($('#txIncomeSource'),incomeSources);fillSubcat($('#txSubcategory'),$('#txCategory').value);fillSubcat($('#recSubcategory'),$('#recCategory').value);fillSubcat($('#instSubcategory'),$('#instCategory').value);$('#txCategory').onchange=()=>fillSubcat($('#txSubcategory'),$('#txCategory').value);$('#recCategory').onchange=()=>fillSubcat($('#recSubcategory'),$('#recCategory').value);$('#instCategory').onchange=()=>fillSubcat($('#instSubcategory'),$('#instCategory').value);$$('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#settingsBtn').onclick=()=>navigate('settings');$('#fab').onclick=()=>open('addDialog');$('#newExpense').onclick=()=>{close('addDialog');resetTxForm('expense');open('txDialog');setTimeout(()=>$('#txAmount').focus(),80)};$('#newIncome').onclick=()=>{close('addDialog');resetTxForm('income');open('txDialog');setTimeout(()=>$('#txAmount').focus(),80)};$('#newRecurring').onclick=()=>{close('addDialog');$('#recEditId').value='';$('#recDialogTitle').textContent='Conta fixa / recorrente';$('#recForm').reset();$('#recStart').value=C.ymd();$('#recDay').value=Number(C.ymd().slice(8));fillSubcat($('#recSubcategory'),$('#recCategory').value);open('recDialog')};$('#newInstallment').onclick=()=>{close('addDialog');$('#instEditId').value='';$('#instDialogTitle').textContent='Compra parcelada';$('#instForm').reset();$('#instStart').value=C.ymd();fillSubcat($('#instSubcategory'),$('#instCategory').value);refreshCardSelects();open('instDialog')};$$('[data-payment]').forEach(b=>b.onclick=()=>syncPaymentUI(b.dataset.payment));syncAppMeta();$('#txForm').onsubmit=saveTx;$('#recForm').onsubmit=saveRecurring;$('#instForm').onsubmit=saveInstallment;$('#instTotal').oninput=updateInstPreview;$('#instCount').oninput=updateInstPreview;$('#prevMonth').onclick=()=>{currentMonth=C.ym(C.addMonths(currentMonth+'-01',-1));render()};$('#nextMonth').onclick=()=>{currentMonth=C.ym(C.addMonths(currentMonth+'-01',1));render()};$('#manageRecurringBtn').onclick=()=>showList('recurring');$('#manageInstallmentsBtn').onclick=()=>showList('installments');$('#manageCardsBtn').onclick=showCards;$('#newCardBtn').onclick=()=>{$('#cardEditId').value='';$('#cardDialogTitle').textContent='Cadastrar cartão';$('#cardForm').reset();open('cardDialog')};$('#cardForm').onsubmit=saveCard;$('#setPinBtn').onclick=setPin;$('#removePinBtn').onclick=removePin;$('#lockNowBtn').onclick=lockApp;$('#unlockBtn').onclick=unlockApp;$('#unlockPin').onkeydown=e=>{if(e.key==='Enter')unlockApp()};$('#exportBtn').onclick=exportBackup;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0])}
(async()=>{db=await openDB();bind();updatePinStatus();await refresh();if(pinConfig())lockApp();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)})().catch(e=>{console.error(e);alert('O Finance OS não conseguiu iniciar. Recarregue a página. Seus dados locais permanecem no aparelho.')});
