(function(root){
  const SCHEMA_VERSION=3, APP_NAME='Finance OS';
  const pad=n=>String(n).padStart(2,'0'); const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`;
  function toCents(v){if(Number.isInteger(v))return v;let s=String(v??'').trim().replace(/R\$/gi,'').replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?Math.round(n*100):0}
  function money(c){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(c)||0)/100)}
  function ym(d){return String(d||'').slice(0,7)} function ymd(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
  function addMonths(s,n){const[y,m,d]=s.split('-').map(Number),x=new Date(y,m-1+n,1),last=new Date(x.getFullYear(),x.getMonth()+1,0).getDate();return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(Math.min(d,last))}`}
  function monthEnd(k){const[y,m]=k.split('-').map(Number);return `${y}-${pad(m)}-${pad(new Date(y,m,0).getDate())}`} const live=x=>!x.deletedAt;
  function installmentSchedule(p){const count=Math.max(1,Number(p.count)||1),total=Number(p.totalCents)||0,base=Math.floor(total/count),rows=[];let assigned=0;for(let i=1;i<=count;i++){const amount=i===count?total-assigned:base;assigned+=amount;rows.push({id:`${p.id}_${i}`,purchaseId:p.id,installmentNumber:i,description:p.description,categoryId:p.categoryId,subcategory:p.subcategory||'',cardId:p.cardId||'',date:addMonths(p.startDate,i-1),amountCents:amount,type:'expense',status:'planned',number:i,count})}return rows}
  function recurringOccurrence(r,k){if(!live(r)||r.active===false||k<ym(r.startDate)||(r.endDate&&k>ym(r.endDate)))return null;const day=Math.min(Number(r.day)||1,Number(monthEnd(k).slice(8)));return {id:`rec_${r.id}_${k}`,recurringId:r.id,description:r.description,categoryId:r.categoryId,subcategory:r.subcategory||'',variable:!!r.variable,date:`${k}-${pad(day)}`,amountCents:Number(r.amountCents)||0,type:r.type||'expense',status:'planned'}}
  function monthProjection(data,k,today=ymd()){const tx=(data.transactions||[]).filter(live).filter(t=>ym(t.date)===k);const rec=(data.recurring||[]).map(r=>recurringOccurrence(r,k)).filter(Boolean);const ins=(data.installments||[]).filter(live).flatMap(installmentSchedule).filter(x=>ym(x.date)===k);const or=new Set(tx.filter(t=>t.recurringId).map(t=>t.recurringId)),oi=new Set(tx.filter(t=>t.purchaseId&&t.installmentNumber).map(t=>`${t.purchaseId}:${t.installmentNumber}`));const planned=[...rec.filter(x=>!or.has(x.recurringId)),...ins.filter(x=>!oi.has(`${x.purchaseId}:${x.installmentNumber}`))];const incomeActual=tx.filter(x=>x.type==='income').reduce((s,x)=>s+x.amountCents,0),expenseActual=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amountCents,0),investmentActual=tx.filter(x=>x.type==='investment'&&x.status!=='planned').reduce((s,x)=>s+x.amountCents,0),incomePlanned=planned.filter(x=>x.type==='income').reduce((s,x)=>s+x.amountCents,0),expensePlanned=planned.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amountCents,0),investmentPlanned=planned.filter(x=>x.type==='investment').reduce((s,x)=>s+x.amountCents,0)+tx.filter(x=>x.type==='investment'&&x.status==='planned').reduce((s,x)=>s+x.amountCents,0);return {incomeActual,expenseActual,investmentActual,incomePlanned,expensePlanned,investmentPlanned,totalIncome:incomeActual+incomePlanned,totalExpense:expenseActual+expensePlanned,totalInvestment:investmentActual+investmentPlanned,free:incomeActual+incomePlanned-expenseActual-expensePlanned-investmentActual-investmentPlanned,remainingCommitments:planned.filter(x=>['expense','investment'].includes(x.type)&&(k>ym(today)||x.date>=today)).reduce((s,x)=>s+x.amountCents,0),transactions:tx,planned}}
  function categoryBreakdown(data,k){const p=monthProjection(data,k),map=new Map();for(const x of [...p.transactions,...p.planned].filter(x=>x.type==='expense'))map.set(x.categoryId||'outros',(map.get(x.categoryId||'outros')||0)+x.amountCents);return [...map].map(([categoryId,amountCents])=>({categoryId,amountCents})).sort((a,b)=>b.amountCents-a.amountCents)}
  function remainingInstallments(p,asOf=ymd()){const s=installmentSchedule(p).filter(x=>x.date>=ym(asOf)+'-01');return {count:s.length,totalCents:s.reduce((a,b)=>a+b.amountCents,0),endDate:s.at(-1)?.date||''}}
  function cardCycleDate(purchaseDate,card){if(!card)return purchaseDate;const d=Number(purchaseDate.slice(8)),close=Number(card.closingDay)||31;return d>close?addMonths(purchaseDate,1):purchaseDate}
  function cardDueDateForCycle(k,card){const [y,m]=k.split('-').map(Number),close=Number(card.closingDay)||31,due=Number(card.dueDay)||1;const base=`${y}-${pad(m)}-01`;const target=due<=close?addMonths(base,1):base;const tk=ym(target),day=Math.min(due,Number(monthEnd(tk).slice(8)));return `${tk}-${pad(day)}`}
  function cardStatement(data,card,k){const tx=(data.transactions||[]).filter(live).filter(t=>t.type==='expense'&&t.cardId===card.id&&ym(cardCycleDate(t.date,card))===k);const ins=(data.installments||[]).filter(live).flatMap(installmentSchedule).filter(x=>x.cardId===card.id&&ym(cardCycleDate(x.date,card))===k);const overridden=new Set(tx.filter(t=>t.purchaseId&&t.installmentNumber).map(t=>`${t.purchaseId}:${t.installmentNumber}`));const planned=ins.filter(x=>!overridden.has(`${x.purchaseId}:${x.installmentNumber}`));const calculatedCents=[...tx,...planned].reduce((s,x)=>s+x.amountCents,0),override=card.invoiceOverrides&&Number.isFinite(Number(card.invoiceOverrides[k]))?Number(card.invoiceOverrides[k]):null,totalCents=override===null?calculatedCents:override;return {transactions:tx,planned,calculatedCents,totalCents,adjustmentCents:totalCents-calculatedCents,overridden:override!==null,dueDate:cardDueDateForCycle(k,card),availableLimitCents:Math.max(0,(Number(card.limitCents)||0)-calculatedCents)}}
  async function sha256Hex(text){const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
  async function createBackupEnvelope(data,exportedAt){const p={app:APP_NAME,backupVersion:2,schemaVersion:SCHEMA_VERSION,exportedAt:exportedAt||new Date().toISOString(),data};return {...p,checksum:await sha256Hex(JSON.stringify(p))}}
  async function validateBackupEnvelope(input){const errors=[];if(!input||input.app!==APP_NAME)errors.push('Arquivo não pertence ao Finance OS');if(![1,2].includes(input?.backupVersion))errors.push('Versão de backup não suportada');if(!input?.data||!Array.isArray(input.data.transactions)||!Array.isArray(input.data.recurring)||!Array.isArray(input.data.installments))errors.push('Estrutura de dados incompleta');if(!errors.length&&input.checksum){const p={app:input.app,backupVersion:input.backupVersion,schemaVersion:input.schemaVersion,exportedAt:input.exportedAt,data:input.data};if(await sha256Hex(JSON.stringify(p))!==input.checksum)errors.push('Checksum inválido')}return {ok:!errors.length,errors,data:input?.data||null}}
  const api={SCHEMA_VERSION,APP_NAME,uid,toCents,money,ym,ymd,addMonths,monthEnd,installmentSchedule,recurringOccurrence,monthProjection,categoryBreakdown,remainingInstallments,cardCycleDate,cardDueDateForCycle,cardStatement,createBackupEnvelope,validateBackupEnvelope};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.FinanceCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
